# compose.yml - Adapted for Coolify from the official OpenEMR repository
#
# Changes:
# 1. Removed the entire "ports" section to let Coolify's reverse proxy handle networking.
# 2. Replaced "env_file" with an "environment" block so Coolify can manage secrets.

version: '3.9'

services:
  mysql:
    image: mariadb:10.6
    container_name: openemr_mysql_1
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    # Replaced 'env_file' with this 'environment' block
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']

  openemr:
    image: openemr/openemr:7.0.3
    container_name: openemr_openemr_1
    restart: always
    depends_on:
      - mysql
    # DELETED the 'ports' section from here
    volumes:
      - openemr-log:/var/www/localhost/htdocs/openemr/sites/default/logs
      - openemr-sites:/var/www/localhost/htdocs/openemr/sites
      - openemr-ccdas:/var/www/localhost/htdocs/openemr/ccdas
      - openemr-documents:/var/www/localhost/htdocs/openemr/documents
      - openemr-edi:/var/www/localhost/htdocs/openemr/edi
      - openemr-era:/var/www/localhost/htdocs/openemr/era
      - openemr-prescriptions:/var/www/localhost/htdocs/openemr/prescriptions
    # Replaced 'env_file' with this 'environment' block
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - OE_USER=admin # Set your desired initial OpenEMR admin username
      - OE_PASS=${OE_PASS} # We will set the initial password in Coolify

volumes:
  mysql-data:
  openemr-log:
  openemr-sites:
  openemr-ccdas:
  openemr-documents:
  openemr-edi:
  openemr-era:
  openemr-prescriptions:
